### ISSUE TITLE
Unable to add new notification

### ISSUE THREAD

**Issue by ScyllaCharybdis** [Jacxk/FreshRSS-DiscordNotifications#3]
Hello,
I just installed but I'm unable to do anything, the Add notification doesn't do anything, just like clicking on "default", so I edited the default .json and add a new RSS and imported from it, but the Save button also doesn't do anything.

**Comment by Jacxk** [comment]
I will check out this issue, everything works on my end. I have around 5 notifications working fine.

**Comment by Jacxk** [comment]
@ScyllaCharybdis So I've found the issue, and I believe is that you didn't enable the extension before editing the configuration. I will post and update warning users to enable the extension first.

**Comment by Jacxk** [comment]
Weird, I did it on a fresh installation. Can you show me the browser console (F12) maybe there's something that could help me replicate it.

**Comment by Jacxk** [comment]
it looks like it might not be loading the javascript files because of the Content Security Policy, maybe you didn't configure FreshRSS correctly if it's under a proxy.

**Comment by Jacxk** [comment]
It seems to be a browser specific error. I will try to replicate it and fix it, looks like I just missed something.

**Comment by Jacxk** [comment]
Try pulling the new changes, hopefully that works. I couldn't replicate the issue, but I tried to fix it according to what I can see from the error.

**Comment by Jacxk** [comment]
I figured that was the issue, but I wanted to fix it without having to remove that, since it's needed in case you save without anything on the required fields.

Luckily you found a fix.
